import type { FontEntry } from './fontList'

// Comprehensive list of fonts typically installed on macOS for canvas-based detection fallback
export const macFontCandidates: FontEntry[] = [
  // Sans-serif
  { family: 'Avenir', category: 'sans-serif', weights: [300, 400, 500, 600, 700, 900], hasItalic: true, source: 'local' },
  { family: 'Avenir Next', category: 'sans-serif', weights: [400, 500, 600, 700], hasItalic: true, source: 'local' },
  { family: 'Avenir Next Condensed', category: 'sans-serif', weights: [400, 500, 600, 700], hasItalic: true, source: 'local' },
  { family: 'Futura', category: 'sans-serif', weights: [400, 500, 700], hasItalic: false, source: 'local' },
  { family: 'Geneva', category: 'sans-serif', weights: [400], hasItalic: false, source: 'local' },
  { family: 'Gill Sans', category: 'sans-serif', weights: [300, 400, 600, 700], hasItalic: true, source: 'local' },
  { family: 'Helvetica', category: 'sans-serif', weights: [300, 400, 700], hasItalic: true, source: 'local' },
  { family: 'Helvetica Neue', category: 'sans-serif', weights: [100, 200, 300, 400, 500, 700], hasItalic: true, source: 'local' },
  { family: 'Lucida Grande', category: 'sans-serif', weights: [400, 700], hasItalic: false, source: 'local' },
  { family: 'Optima', category: 'sans-serif', weights: [400, 700], hasItalic: true, source: 'local' },
  { family: 'SF Pro', category: 'sans-serif', weights: [100, 200, 300, 400, 500, 600, 700, 800, 900], hasItalic: true, source: 'local' },
  { family: 'SF Pro Display', category: 'sans-serif', weights: [100, 200, 300, 400, 500, 600, 700, 800, 900], hasItalic: true, source: 'local' },
  { family: 'SF Pro Text', category: 'sans-serif', weights: [100, 200, 300, 400, 500, 600, 700, 800, 900], hasItalic: true, source: 'local' },
  { family: 'SF Pro Rounded', category: 'sans-serif', weights: [100, 200, 300, 400, 500, 600, 700, 800, 900], hasItalic: false, source: 'local' },
  { family: 'SF Compact', category: 'sans-serif', weights: [100, 200, 300, 400, 500, 600, 700, 800, 900], hasItalic: true, source: 'local' },
  { family: 'System Font', category: 'sans-serif', weights: [400, 700], hasItalic: false, source: 'local' },
  { family: 'Trebuchet MS', category: 'sans-serif', weights: [400, 700], hasItalic: true, source: 'local' },
  { family: 'Verdana', category: 'sans-serif', weights: [400, 700], hasItalic: true, source: 'local' },
  { family: 'Arial', category: 'sans-serif', weights: [400, 700], hasItalic: true, source: 'local' },
  { family: 'Arial Narrow', category: 'sans-serif', weights: [400, 700], hasItalic: true, source: 'local' },
  { family: 'Arial Rounded MT Bold', category: 'sans-serif', weights: [700], hasItalic: false, source: 'local' },
  { family: 'Tahoma', category: 'sans-serif', weights: [400, 700], hasItalic: false, source: 'local' },
  { family: 'Impact', category: 'sans-serif', weights: [400], hasItalic: false, source: 'local' },

  // Serif
  { family: 'Baskerville', category: 'serif', weights: [400, 600, 700], hasItalic: true, source: 'local' },
  { family: 'Big Caslon', category: 'serif', weights: [500], hasItalic: false, source: 'local' },
  { family: 'Bodoni 72', category: 'serif', weights: [400, 700], hasItalic: true, source: 'local' },
  { family: 'Bodoni 72 Oldstyle', category: 'serif', weights: [400, 700], hasItalic: true, source: 'local' },
  { family: 'Bodoni 72 Smallcaps', category: 'serif', weights: [400], hasItalic: false, source: 'local' },
  { family: 'Book Antiqua', category: 'serif', weights: [400, 700], hasItalic: true, source: 'local' },
  { family: 'Bookman Old Style', category: 'serif', weights: [400, 700], hasItalic: true, source: 'local' },
  { family: 'Cambria', category: 'serif', weights: [400, 700], hasItalic: true, source: 'local' },
  { family: 'Cochin', category: 'serif', weights: [400, 700], hasItalic: true, source: 'local' },
  { family: 'Didot', category: 'serif', weights: [400, 700], hasItalic: true, source: 'local' },
  { family: 'Georgia', category: 'serif', weights: [400, 700], hasItalic: true, source: 'local' },
  { family: 'Goudy Old Style', category: 'serif', weights: [400, 700], hasItalic: true, source: 'local' },
  { family: 'Hoefler Text', category: 'serif', weights: [400, 700], hasItalic: true, source: 'local' },
  { family: 'Iowan Old Style', category: 'serif', weights: [400, 700], hasItalic: true, source: 'local' },
  { family: 'New York', category: 'serif', weights: [400, 500, 600, 700], hasItalic: true, source: 'local' },
  { family: 'Palatino', category: 'serif', weights: [400, 700], hasItalic: true, source: 'local' },
  { family: 'Palatino Linotype', category: 'serif', weights: [400, 700], hasItalic: true, source: 'local' },
  { family: 'Superclarendon', category: 'serif', weights: [400, 700, 900], hasItalic: true, source: 'local' },
  { family: 'Times New Roman', category: 'serif', weights: [400, 700], hasItalic: true, source: 'local' },

  // Monospace
  { family: 'American Typewriter', category: 'mono', weights: [300, 400, 600, 700], hasItalic: false, source: 'local' },
  { family: 'Andale Mono', category: 'mono', weights: [400], hasItalic: false, source: 'local' },
  { family: 'Courier', category: 'mono', weights: [400, 700], hasItalic: true, source: 'local' },
  { family: 'Courier New', category: 'mono', weights: [400, 700], hasItalic: true, source: 'local' },
  { family: 'Menlo', category: 'mono', weights: [400, 700], hasItalic: true, source: 'local' },
  { family: 'Monaco', category: 'mono', weights: [400], hasItalic: false, source: 'local' },
  { family: 'SF Mono', category: 'mono', weights: [300, 400, 500, 600, 700], hasItalic: true, source: 'local' },

  // Display
  { family: 'Academy Engraved LET', category: 'display', weights: [400], hasItalic: false, source: 'local' },
  { family: 'Chalkduster', category: 'display', weights: [400], hasItalic: false, source: 'local' },
  { family: 'Comic Sans MS', category: 'display', weights: [400, 700], hasItalic: true, source: 'local' },
  { family: 'Copperplate', category: 'display', weights: [300, 400, 700], hasItalic: false, source: 'local' },
  { family: 'Herculanum', category: 'display', weights: [400], hasItalic: false, source: 'local' },
  { family: 'Marker Felt', category: 'display', weights: [400, 700], hasItalic: false, source: 'local' },
  { family: 'Noteworthy', category: 'display', weights: [300, 700], hasItalic: false, source: 'local' },
  { family: 'Papyrus', category: 'display', weights: [400], hasItalic: false, source: 'local' },
  { family: 'Phosphate', category: 'display', weights: [400], hasItalic: false, source: 'local' },
  { family: 'Rockwell', category: 'display', weights: [400, 700], hasItalic: true, source: 'local' },
  { family: 'SignPainter', category: 'display', weights: [400], hasItalic: false, source: 'local' },
  { family: 'Skia', category: 'display', weights: [400], hasItalic: false, source: 'local' },
  { family: 'Trattatello', category: 'display', weights: [400], hasItalic: false, source: 'local' },

  // Script / Handwriting
  { family: 'Apple Chancery', category: 'script', weights: [400], hasItalic: false, source: 'local' },
  { family: 'Bradley Hand', category: 'script', weights: [700], hasItalic: false, source: 'local' },
  { family: 'Brush Script MT', category: 'script', weights: [400], hasItalic: true, source: 'local' },
  { family: 'Corsiva Hebrew', category: 'script', weights: [400, 700], hasItalic: false, source: 'local' },
  { family: 'Luminari', category: 'script', weights: [400], hasItalic: false, source: 'local' },
  { family: 'Savoye LET', category: 'script', weights: [400], hasItalic: false, source: 'local' },
  { family: 'Snell Roundhand', category: 'script', weights: [400, 700, 900], hasItalic: false, source: 'local' },
  { family: 'Zapfino', category: 'script', weights: [400], hasItalic: false, source: 'local' },
]
